services:
  postgis:
    image: postgis/postgis:17-3.5-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  maildev:
    build:
      context: .
      dockerfile: ./apps/backend/maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./apps/backend/Dockerfile
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}

volumes:
  pgdata:
